import { Course } from "@/types/course";
import { Task } from "@/types/task";

export const courses: Course[] = [
  {
    id: '1',
    name: 'Data Structures & Algorithms',
    color: '#3b82f6',
    progress: 65,
    examDate: '2026-04-25',
    topics: [
      { id: 't1', week: 1, title: 'Introduction to Algorithms', completed: true },
      { id: 't2', week: 1, title: 'Big O Notation', completed: true },
      { id: 't3', week: 2, title: 'Arrays and Linked Lists', completed: true },
      { id: 't4', week: 2, title: 'Stacks and Queues', completed: false },
      { id: 't5', week: 3, title: 'Trees and Graphs', completed: false },
      { id: 't6', week: 3, title: 'Sorting Algorithms', completed: false },
    ],
    assignments: [
      { id: 'a1', title: 'Assignment 1: Array Problems', dueDate: '2026-04-05', completed: true },
      { id: 'a2', title: 'Assignment 2: Linked List Implementation', dueDate: '2026-04-12', completed: false },
      { id: 'a3', title: 'Assignment 3: Tree Traversal', dueDate: '2026-04-19', completed: false },
    ],
  },
  {
    id: '2',
    name: 'Machine Learning',
    color: '#10b981',
    progress: 40,
    examDate: '2026-04-28',
    topics: [
      { id: 't7', week: 1, title: 'Introduction to ML', completed: true },
      { id: 't8', week: 1, title: 'Linear Regression', completed: true },
      { id: 't9', week: 2, title: 'Logistic Regression', completed: false },
      { id: 't10', week: 2, title: 'Neural Networks Basics', completed: false },
      { id: 't11', week: 3, title: 'Deep Learning', completed: false },
    ],
    assignments: [
      { id: 'a4', title: 'Lab 1: Linear Regression', dueDate: '2026-04-08', completed: true },
      { id: 'a5', title: 'Lab 2: Classification Models', dueDate: '2026-04-15', completed: false },
    ],
  },
  {
    id: '3',
    name: 'Web Development',
    color: '#f59e0b',
    progress: 75,
    examDate: '2026-04-22',
    topics: [
      { id: 't12', week: 1, title: 'HTML & CSS Fundamentals', completed: true },
      { id: 't13', week: 1, title: 'JavaScript Basics', completed: true },
      { id: 't14', week: 2, title: 'React Framework', completed: true },
      { id: 't15', week: 2, title: 'State Management', completed: false },
      { id: 't16', week: 3, title: 'Backend with Node.js', completed: false },
    ],
    assignments: [
      { id: 'a6', title: 'Project 1: Portfolio Website', dueDate: '2026-04-10', completed: true },
      { id: 'a7', title: 'Project 2: Todo App', dueDate: '2026-04-17', completed: false },
    ],
  },
];

export const tasks: Task[] = [
  // Today's tasks
  {
    id: 'task1',
    title: 'Read Chapter 4: Stacks and Queues',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 45,
    priority: 'high',
    type: 'reading',
    date: '2026-03-31',
  },
  {
    id: 'task2',
    title: 'Watch Lecture 7: Stack Implementation',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 60,
    priority: 'high',
    type: 'lecture',
    date: '2026-03-31',
  },
  {
    id: 'task3',
    title: 'Solve exercises 15-20',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 90,
    priority: 'medium',
    type: 'exercise',
    date: '2026-03-31',
  },
  {
    id: 'task4',
    title: 'Read Chapter 3: Logistic Regression',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: true,
    estimatedTime: 50,
    priority: 'medium',
    type: 'reading',
    date: '2026-03-31',
  },
  {
    id: 'task5',
    title: 'Review React Hooks documentation',
    courseId: '3',
    courseName: 'Web Development',
    courseColor: '#f59e0b',
    completed: true,
    estimatedTime: 30,
    priority: 'low',
    type: 'review',
    date: '2026-03-31',
  },
  // Tomorrow's tasks
  {
    id: 'task6',
    title: 'Watch Lecture 8: Neural Networks',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 75,
    priority: 'high',
    type: 'lecture',
    date: '2026-04-01',
  },
  {
    id: 'task7',
    title: 'Complete Lab 2 exercises',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 120,
    priority: 'high',
    type: 'exercise',
    date: '2026-04-01',
  },
  {
    id: 'task8',
    title: 'Read Chapter 5: Trees',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 60,
    priority: 'medium',
    type: 'reading',
    date: '2026-04-01',
  },
];

export const weeklyProgress = {
  completed: 12,
  pending: 8,
  totalTasks: 20,
  studyHours: 15.5,
  targetHours: 20,
};
