import { Course } from "@/types/course";
import { Task } from "@/types/task";

export const courses: Course[] = [
  {
    id: '1',
    name: 'Data Structures & Algorithms',
    color: '#3b82f6',
    progress: 78,
    examDate: '2026-04-25',
    topics: [
      { id: 't1', week: 1, title: 'Introduction to Algorithms', completed: true },
      { id: 't2', week: 1, title: 'Big O Notation', completed: true },
      { id: 't3', week: 2, title: 'Arrays and Linked Lists', completed: true },
      { id: 't4', week: 2, title: 'Stacks and Queues', completed: true },
      { id: 't5', week: 3, title: 'Trees and Graphs', completed: true },
      { id: 't6', week: 3, title: 'Sorting Algorithms', completed: true },
      { id: 't7', week: 4, title: 'Searching Algorithms', completed: true },
      { id: 't8', week: 4, title: 'Hash Tables', completed: false },
      { id: 't9', week: 5, title: 'Heaps and Priority Queues', completed: false },
      { id: 't10', week: 5, title: 'Dynamic Programming Basics', completed: false },
    ],
    assignments: [
      { id: 'a1', title: 'Assignment 1: Array Problems', dueDate: '2026-04-05', completed: true },
      { id: 'a2', title: 'Assignment 2: Linked List Implementation', dueDate: '2026-04-12', completed: true },
      { id: 'a3', title: 'Assignment 3: Tree Traversal', dueDate: '2026-04-19', completed: false },
      { id: 'a4', title: 'Assignment 4: Graph Shortest Path', dueDate: '2026-04-23', completed: false },
    ],
  },
  {
    id: '2',
    name: 'Machine Learning',
    color: '#10b981',
    progress: 58,
    examDate: '2026-04-28',
    topics: [
      { id: 't11', week: 1, title: 'Introduction to ML', completed: true },
      { id: 't12', week: 1, title: 'Linear Regression', completed: true },
      { id: 't13', week: 2, title: 'Logistic Regression', completed: true },
      { id: 't14', week: 2, title: 'Model Evaluation Metrics', completed: true },
      { id: 't15', week: 3, title: 'Neural Networks Basics', completed: false },
      { id: 't16', week: 3, title: 'Gradient Descent and Optimization', completed: false },
      { id: 't17', week: 4, title: 'Deep Learning', completed: false },
      { id: 't18', week: 4, title: 'Regularization Techniques', completed: false },
      { id: 't19', week: 5, title: 'Decision Trees and Random Forests', completed: false },
    ],
    assignments: [
      { id: 'a5', title: 'Lab 1: Linear Regression', dueDate: '2026-04-08', completed: true },
      { id: 'a6', title: 'Lab 2: Classification Models', dueDate: '2026-04-15', completed: false },
      { id: 'a7', title: 'Lab 3: Neural Network Tuning', dueDate: '2026-04-22', completed: false },
    ],
  },
  {
    id: '3',
    name: 'Web Development',
    color: '#f59e0b',
    progress: 82,
    examDate: '2026-04-22',
    topics: [
      { id: 't20', week: 1, title: 'HTML & CSS Fundamentals', completed: true },
      { id: 't21', week: 1, title: 'JavaScript Basics', completed: true },
      { id: 't22', week: 2, title: 'React Framework', completed: true },
      { id: 't23', week: 2, title: 'State Management', completed: true },
      { id: 't24', week: 3, title: 'Backend with Node.js', completed: true },
      { id: 't25', week: 3, title: 'REST APIs', completed: false },
      { id: 't26', week: 4, title: 'Authentication and Authorization', completed: false },
      { id: 't27', week: 4, title: 'Deployment and CI/CD Basics', completed: false },
    ],
    assignments: [
      { id: 'a8', title: 'Project 1: Portfolio Website', dueDate: '2026-04-10', completed: true },
      { id: 'a9', title: 'Project 2: Todo App', dueDate: '2026-04-17', completed: false },
      { id: 'a10', title: 'Project 3: Full Stack Blog App', dueDate: '2026-04-21', completed: false },
    ],
  },
  {
    id: '4',
    name: 'Database Systems',
    color: '#8b5cf6',
    progress: 46,
    examDate: '2026-04-30',
    topics: [
      { id: 't28', week: 1, title: 'Introduction to Databases', completed: true },
      { id: 't29', week: 1, title: 'ER Diagrams', completed: true },
      { id: 't30', week: 2, title: 'Relational Model', completed: true },
      { id: 't31', week: 2, title: 'SQL Basics', completed: false },
      { id: 't32', week: 3, title: 'Joins and Subqueries', completed: false },
      { id: 't33', week: 3, title: 'Normalization', completed: false },
      { id: 't34', week: 4, title: 'Transactions and Concurrency', completed: false },
    ],
    assignments: [
      { id: 'a11', title: 'Worksheet 1: ER Modeling', dueDate: '2026-04-11', completed: true },
      { id: 'a12', title: 'Worksheet 2: SQL Queries', dueDate: '2026-04-18', completed: false },
      { id: 'a13', title: 'Mini Project: Library Database', dueDate: '2026-04-26', completed: false },
    ],
  },
];

export const tasks: Task[] = [
  // Today's tasks - 2026-04-09
  {
    id: 'task1',
    title: 'Review hash table collision strategies',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 40,
    priority: 'high',
    type: 'review',
    date: '2026-04-09',
  },
  {
    id: 'task2',
    title: 'Solve 5 graph traversal problems',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 90,
    priority: 'high',
    type: 'exercise',
    date: '2026-04-09',
  },
  {
    id: 'task3',
    title: 'Read chapter on Neural Networks Basics',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 55,
    priority: 'high',
    type: 'reading',
    date: '2026-04-09',
  },
  {
    id: 'task4',
    title: 'Finish API routes for blog project',
    courseId: '3',
    courseName: 'Web Development',
    courseColor: '#f59e0b',
    completed: true,
    estimatedTime: 80,
    priority: 'medium',
    type: 'project',
    date: '2026-04-09',
  },
  {
    id: 'task5',
    title: 'Practice SQL SELECT and WHERE queries',
    courseId: '4',
    courseName: 'Database Systems',
    courseColor: '#8b5cf6',
    completed: false,
    estimatedTime: 60,
    priority: 'medium',
    type: 'exercise',
    date: '2026-04-09',
  },

  // Tomorrow - 2026-04-10
  {
    id: 'task6',
    title: 'Submit Project 1: Portfolio Website',
    courseId: '3',
    courseName: 'Web Development',
    courseColor: '#f59e0b',
    completed: false,
    estimatedTime: 30,
    priority: 'high',
    type: 'assignment',
    date: '2026-04-10',
  },
  {
    id: 'task7',
    title: 'Watch lecture on Gradient Descent',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 70,
    priority: 'medium',
    type: 'lecture',
    date: '2026-04-10',
  },
  {
    id: 'task8',
    title: 'Review normalization examples',
    courseId: '4',
    courseName: 'Database Systems',
    courseColor: '#8b5cf6',
    completed: false,
    estimatedTime: 45,
    priority: 'medium',
    type: 'review',
    date: '2026-04-10',
  },

  // Upcoming weekend
  {
    id: 'task9',
    title: 'Complete Assignment 2 final checks',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 50,
    priority: 'high',
    type: 'assignment',
    date: '2026-04-11',
  },
  {
    id: 'task10',
    title: 'Implement binary heap from scratch',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 100,
    priority: 'medium',
    type: 'project',
    date: '2026-04-11',
  },
  {
    id: 'task11',
    title: 'Prepare notes for classification models lab',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 65,
    priority: 'medium',
    type: 'review',
    date: '2026-04-11',
  },
  {
    id: 'task12',
    title: 'Submit Worksheet 1: ER Modeling',
    courseId: '4',
    courseName: 'Database Systems',
    courseColor: '#8b5cf6',
    completed: true,
    estimatedTime: 20,
    priority: 'high',
    type: 'assignment',
    date: '2026-04-11',
  },
  {
    id: 'task13',
    title: 'Build protected routes for the blog app',
    courseId: '3',
    courseName: 'Web Development',
    courseColor: '#f59e0b',
    completed: false,
    estimatedTime: 95,
    priority: 'high',
    type: 'project',
    date: '2026-04-12',
  },
  {
    id: 'task14',
    title: 'Submit Assignment 2: Linked List Implementation',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: true,
    estimatedTime: 25,
    priority: 'high',
    type: 'assignment',
    date: '2026-04-12',
  },
  {
    id: 'task15',
    title: 'Practice JOIN queries in SQL',
    courseId: '4',
    courseName: 'Database Systems',
    courseColor: '#8b5cf6',
    completed: false,
    estimatedTime: 75,
    priority: 'medium',
    type: 'exercise',
    date: '2026-04-12',
  },

  // Next study block
  {
    id: 'task16',
    title: 'Read dynamic programming basics',
    courseId: '1',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#3b82f6',
    completed: false,
    estimatedTime: 70,
    priority: 'medium',
    type: 'reading',
    date: '2026-04-13',
  },
  {
    id: 'task17',
    title: 'Train and evaluate a simple neural network',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 120,
    priority: 'high',
    type: 'project',
    date: '2026-04-13',
  },
  {
    id: 'task18',
    title: 'Create authentication flow wireframe',
    courseId: '3',
    courseName: 'Web Development',
    courseColor: '#f59e0b',
    completed: false,
    estimatedTime: 60,
    priority: 'low',
    type: 'other',
    date: '2026-04-13',
  },
  {
    id: 'task19',
    title: 'Read about transactions and ACID properties',
    courseId: '4',
    courseName: 'Database Systems',
    courseColor: '#8b5cf6',
    completed: false,
    estimatedTime: 50,
    priority: 'medium',
    type: 'reading',
    date: '2026-04-14',
  },
  {
    id: 'task20',
    title: 'Complete Lab 2: Classification Models',
    courseId: '2',
    courseName: 'Machine Learning',
    courseColor: '#10b981',
    completed: false,
    estimatedTime: 140,
    priority: 'high',
    type: 'project',
    date: '2026-04-15',
  },
];

export const weeklyProgress = {
  completed: 18,
  pending: 12,
  totalTasks: 30,
  studyHours: 23.5,
  targetHours: 28,
};
